eduquest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    #About User
    path('user/<int:user_id>/', views.user_detail, name='user_detail'),
    #About Profile
    path('user/<int:pk>/update', views.ProfileUpdate.as_view(), name='profile_update'),
    #About Quest
    path('quests/', views.quests_index, name='quests_index'),
    path('quests/<int:pk>/', views.quests_detail, name='quests_detail'),
    #About Subjects, main index is also here
    path('subjects/', views.subjects_index, name='index'),
    path('subjects/create', views.subjects_create, name='subjects_create'),
    path('subjects/<int:pk>/', views.subjects_detail, name='subjects_detail'),
    path('subjects/<int:pk>/update/', views.subjects_update, name='subjects_update'),
    path('subjects/<int:pk>/delete/', views.subjects_delete, name='subjects_delete'),
    #About Assignment
    path('assignments/create/<int:pk>/', views.AssignmentCreate.as_view(), name='assignments_create'),
    path('assignments/<int:pk>', views.AssignmentDetail.as_view(), name='assignments_detail'),
    path('assignments/<int:pk>/update/', views.AssignmentUpdate.as_view(), name='assignments_update'),
    path('assignments/<int:pk>/delete/', views.AssignmentDelete.as_view(), name='assignments_delete'),
    #About Leaderboards
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    #Signup
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from datetime import date, timedelta

FIELD = (
    ('MA', 'Maths'),
    ('SS', 'Social Science'),
    ('SC', 'Science'),
    ('AR', 'Arts'),
    ('HU', 'Humanities')
)

GRADE = (
    ('A', 'A - Excellent'),
    ('B', 'B - Good'),
    ('C', 'C - Satisfactory'),
    ('D', 'D - Limited'),
    ('E', 'E - Very Low'),
    ('F', 'F - Failed/Incomplete')
)

STATUS = (
    ('NS', 'Not Started'),
    ('IP', 'In Progress'),
    ('CM', 'Completed')
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    email = models.EmailField(max_length=100, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    school_year = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(12)],
        null=True, blank=True
    )
    xp = models.IntegerField(
        default=0,
        validators=[MinValueValidator(0)]
    )
    avatar_url = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('user_detail', kwargs={'user_id': self.user.id})

# Automatically add a profile for the user when a user is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def one_day_after():
    date.today() + timedelta(days=1)

class Subject(models.Model):
    name = models.CharField(max_length=100)
    field = models.CharField(
        max_length=2,
        choices=FIELD,
        default=FIELD[4][0]
    )
    start_date = models.DateField(("Date"), default=date.today)
    end_date = models.DateField(("Date"), default=date.today)
    progress = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=1
    )
    exam_date = models.DateField(("Date"), default=date.today() + timedelta(days=1))
    grade = models.CharField(
        max_length=1,
        choices=GRADE,
        default=GRADE[2][0]
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    # need to confirm the view to send people to
    def get_absolute_url(self):
        return reverse("model_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        # Calculate progress based on the proximity of today's date to start and end dates
        today = date.today()
        # Handling case where start and end dates are the same
        if self.start_date == self.end_date:
            self.progress = 100
        else:
            days_total = (self.end_date - self.start_date).days
            days_passed = (today - self.start_date).days
            progress = min(100, max(0, int((days_passed / days_total) * 100)))

            self.progress = progress

        super().save(*args, **kwargs)

class Assignment(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    due_date = models.DateField(default=date.today)
    complete_date = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default=STATUS[0][0]
    )

    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Quest(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    xp_earned = models.IntegerField(
        validators=[MinValueValidator(1)])
    badge_image_url = models.URLField(max_length=200)

    def __str__(self):
        return self.name

    @staticmethod
    def is_grandmaster(user):
        # Check if the user has achieved all quests except 'Grandmaster of EduQuest' (to be eligible for the Grandmaster quest)
        all_quests_except_grandmaster = Quest.objects.exclude(name='Grandmaster of EduQuest')
        return all(ProfileAchievement.has_quest_achievement(user, quest.name) for quest in all_quests_except_grandmaster)



class ProfileAchievement(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quest = models.ForeignKey(Quest, on_delete=models.CASCADE)
    date_achieved = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.first_name} - {self.quest.name} - {self.date_achieved}"

    @staticmethod
    def has_quest_achievement(user, quest_name):
        # Check if the user has achieved a specific quest
        return ProfileAchievement.objects.filter(user=user, quest__name=quest_name).exists()

    @staticmethod
    def get_quest_xp(quest_name):
        # Get the XP earned for a specific quest
        return Quest.objects.get(name=quest_name).xp_earned

main_app/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile, Subject, Assignment, Quest, ProfileAchievement, User
from .forms import SubjectForm
from datetime import date, datetime
from .quests import grant_name_to_face_quest, grant_grandmaster_quest, grant_exam_slayer_quest, grant_getting_started_quest, grant_subject_explorer_quest, grant_multitasking_maven_quest, grant_elite_leaderboard_quest, grant_master_the_basics_quest, grant_time_management_pro_quest, grant_assignment_conqueror_quest

# ------------ #
#  Basic Views #
# ------------ #
def home(request):
    return render(request, 'home.html')

# ------------ #
#  User Views  #
# ------------ #
@login_required
def user_detail(request, user_id):
    user = User.objects.get(id=user_id)
    profile = user.profile
    achievements = ProfileAchievement.objects.filter(user=user)
    return render(request, 'user/user_detail.html', {
       'user': user, 'profile': profile, 'achievements': achievements
    })

# ------------- #
# Profile Views #
# ------------- #
class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['email', 'first_name', 'last_name', 'school_year']

    def form_valid(self, form):
        # Check if the first name and last name have been changed
        if set(form.changed_data).intersection({'first_name', 'last_name'}):
            grant_name_to_face_quest(form.instance.user)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('user_detail', kwargs={'user_id': self.object.user.id})


# ----------- #
# Quest Views #
# ----------- #
@login_required
def quests_index(request):
    user = request.user
    all_quests = Quest.objects.all()

    # Check & Grant (if eligible) Grandmaster of EduQuest achievement
    grant_grandmaster_quest(user)

    # Filter ProfileAchievement objects for the current user
    achieved_quests = ProfileAchievement.objects.filter(user=user)
    achieved_quest_ids = list(achieved_quests.values_list('quest__id', flat=True))
    uncompleted_quests = all_quests.exclude(id__in=achieved_quests.values_list('quest', flat=True))

    return render(request, 'quests/quests_index.html', {'all_quests': all_quests, 'achieved_quest_ids': achieved_quest_ids, 'uncompleted_quests': uncompleted_quests })

@login_required
def quests_detail(request, pk):
    quest = get_object_or_404(Quest, pk=pk)
    user = request.user
    # Check if the user has achieved the quest - returns a true or false
    achieved_quest = ProfileAchievement.objects.filter(user=user, quest=quest).exists()
    return render(request, 'quests/quests_detail.html', {'quest': quest, 'achieved_quest': achieved_quest })

# -------------- #
# Subjects Views #
# -------------- #
@login_required
def subjects_index(request):
    subjects = Subject.objects.filter(user=request.user)
    upcoming_exams = subjects.filter(exam_date__gte=date.today()).order_by('exam_date')
    # Check & Grant Exam Slayer quest
    grant_exam_slayer_quest(request.user)
    # Converting subjects and upcoming exams data into JSON format
    subjects_data = json.dumps([
        {'name': subject.name, 'progress': subject.progress} for subject in subjects
    ])
    upcoming_exams_data = json.dumps([
        {'name': exam.name, 'exam_date': exam.exam_date.strftime('%d-%m-%Y')} for exam in upcoming_exams
    ])
    all_quests = Quest.objects.all()

    context = {
        'subjects': subjects,
        'upcoming_exams_data': upcoming_exams_data,
        'all_quests': all_quests,
        'subjects_json': subjects_data
    }
    return render(request, 'subjects/index.html', context)

@login_required
def subjects_detail(request, pk):
    subject = get_object_or_404(Subject, pk=pk)
    current_date = datetime.now().date()
    exam_date = subject.exam_date
    exam_has_passed = exam_date < current_date

    return render(request, 'subjects/subject_detail.html', {'subject': subject, 'current_date': current_date, 'exam_has_passed': exam_has_passed, 'subject_id': pk,})

@login_required
def subjects_create(request):
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            subject = form.save(commit=False)
            subject.user = request.user
            subject.save()

            # Quest checks for Getting Started, Exam Slayer & Subject Explorer
            grant_getting_started_quest(request.user, subject)
            grant_exam_slayer_quest(request.user)
            grant_subject_explorer_quest(request.user)

            return redirect('subjects_detail', pk=subject.pk)
    else:
        form = SubjectForm()

    return render(request, 'subjects/subject_form.html', {'form': form, 'subject': None})

@login_required
def subjects_update(request, pk):
    subject = get_object_or_404(Subject, pk=pk)

    if request.method == 'POST':
        form = SubjectForm(request.POST, instance=subject)
        if form.is_valid():
            form.save()

            # Quest checks Subject Explorer & Multitasking Maven
            grant_subject_explorer_quest(request.user)
            grant_multitasking_maven_quest(request.user)

            return redirect('subjects_detail', pk=pk)
    else:
        form = SubjectForm(instance=subject)

    return render(request, 'subjects/subject_form.html', {'form': form, 'subject': subject})

@login_required
def subjects_delete(request, pk):
    subject = get_object_or_404(Subject, pk=pk)
    if request.method == 'POST':

        subject.delete()
        return redirect('index')

    return render(request, 'subjects/subject_delete.html', {'subject': subject})

# ------------------ #
# About Leaderboards #
# ------------------ #
def leaderboard(request):
    leaderboard_data = Profile.objects.all().order_by('-xp')
    current_user = request.user

    if current_user.is_authenticated:
            grant_elite_leaderboard_quest()

    context = {
        'leaderboard_data': leaderboard_data,
    }
    return render(request, 'main_app/leaderboard.html', context)

# ----------------- #
# Assignments Views #
# ----------------- #
class AssignmentDetail(LoginRequiredMixin, DetailView):
    model = Assignment
    template_name = 'assignments/assignment_detail.html'
    context_object_name = 'assignment'

class AssignmentCreate(LoginRequiredMixin, CreateView):
    model = Assignment
    template_name = 'assignments/assignment_form.html'
    context_object_name = 'subjects'
    fields = ['name', 'description', 'due_date', 'status', 'subject']

    def form_valid(self, form):
        form.instance.user = self.request.user
        # Checks if the status is 'completed', if so, sets the complete_date to today
        if form.cleaned_data['status'] == 'CM':
            form.instance.complete_date = timezone.now().date()

        response = super().form_valid(form)

        # Quest check for Master the Basics
        grant_master_the_basics_quest(self.request.user)

        return response

    def get_initial(self):
        initial = super().get_initial()
        # If the subject id is passed in the URL, set it as the initial value for the subject field
        subject_id = self.kwargs.get('pk')
        if subject_id:
            subject = get_object_or_404(Subject, pk=subject_id, user=self.request.user)
            initial['subject'] = subject
        return initial

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # Filter subjects to only those owned by the current user
        form.fields['subject'].queryset = self.request.user.subject_set.all()
        return form

    def get_success_url(self):
        # Access the newly created assignment object and then its subject
        assignment = self.object
        return reverse('subjects_detail', kwargs={'pk': assignment.subject.pk})

class AssignmentUpdate(LoginRequiredMixin, UpdateView):
    model = Assignment
    template_name = 'assignments/assignment_form.html'
    context_object_name = 'assignment'
    fields = ['name', 'description', 'due_date', 'status', 'subject']

    # Overriding the form_valid to quest elibibility and add complete date (if they change the status)
    def form_valid(self, form):
        if form.cleaned_data['status'] == 'CM':
            # Checks if the status is 'completed', if so, sets the complete_date to today
            form.instance.complete_date = timezone.now().date()

        response = super().form_valid(form)

        # Quest Checks for Time Management Pro, Assignment Conqueror
        grant_time_management_pro_quest(self.request.user)
        grant_assignment_conqueror_quest(self.request.user)

        return response

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # Filter subjects to only those owned by the current user
        form.fields['subject'].queryset = self.request.user.subject_set.all()
        return form

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse('assignments_detail', kwargs={'pk': pk})

class AssignmentDelete(LoginRequiredMixin, DeleteView):
    model = Assignment
    template_name = 'assignments/assignment_delete.html'
    context_object_name = 'assignment'

    def get_success_url(self):
        # Get the subject's pk from the created assignment instance
        subject_pk = self.object.subject.pk
        # Redirect to the subjects_detail page
        return reverse_lazy('subjects_detail', kwargs={'pk': subject_pk})

# ------------ #

main_app/templates/assignments/assignment_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Delete Assignment{% endblock %}

{% block content %}
<div class="delete-content">
  <h2>Delete Assignment</h2>
  <p>Are you sure you want to delete this assignment?</p>
  <form method="post" action="#" class="delete-form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'assignments_detail' pk=assignment.pk %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock %}

main_app/templates/assignments/assignment_detail.html
{% extends 'base.html' %} {% block title %}Assignments{% endblock %}
{% block content %}
<div class="container">
  <div class="subject-details-card mx-auto">
    <div class="subject-details-header">
      <h2>{{ assignment.name }}</h2>
    </div>
    <div class="subject-details-body" style="padding: 20px">
      <div class="row">
        <div class="col-md-6">
          <div class="details-section">
            <h3>Description</h3>
            <p>{{ assignment.description }}</p>
          </div>
          <div class="details-section">
            <h3>Due_Date</h3>
            <p>{{ assignment.due_date }}</p>
          </div>
          <div class="details-section">
            <h3>Status</h3>
            <p>{{ assignment.get_status_display }}</p>
          </div>
          {% if assignment.complete_date %}
          <div class="details-section">
            <h3>Completed Date</h3>
            <p>{{ assignment.complete_date }}</p>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col-md-12 text-center" style="padding: 20px">
        <a
          href="{% url 'assignments_update' pk=assignment.pk %}"
          class="btn btn-secondary me-5"
          style="border: 1px solid white"
          >Edit</a
        >
        <a
          href="{% url 'assignments_delete' pk=assignment.pk %}"
          class="btn btn-danger"
          >Delete</a
        >
      </div>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-md-12 text-center" style="padding: 20px;">
      <a href="{% url 'subjects_detail' pk=assignment.subject.pk %}" class="btn btn-primary">Back To
        {{assignment.subject.name}} Detail</a>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/assignments/assignment_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
{% if assignment.pk %}
Update Assignment
{% else %}
Create Assignment
{% endif %}
{% endblock %}

{% block content %}


<div class="assignment-form">
  <div class="card">
    <div class="card-header">
      <h2 class="mb-0">
        {% if assignment.pk %}
        Update Assignment
        {% else %}
        Create Assignment
        {% endif %}
      </h2>
    </div>
    <div class="card-body">
      <form method="post" class="fantasy-form">
        {% csrf_token %}
        {% if assignment.pk %}
        <!-- Fields for updating an existing assignment -->
        <input type="hidden" name="action" value="update">
        <input type="hidden" name="assignment_id" value="{{ assignment.pk }}">
        {% else %}
        <!-- Fields for creating a new assignment -->
        <input type="hidden" name="action" value="create">
        {% endif %}
        <div class="input-group mb-3">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="input-group mb-3">
          {{ form.description|as_crispy_field }}
        </div>
        <div class="input-group mb-3">
          {{ form.due_date|as_crispy_field }}
        </div>
        <div class="input-group mb-3">
          {{ form.status|as_crispy_field }}
        </div>
        <div class="input-group mb-3">
          {{ form.subject|as_crispy_field }}
        </div>
        <div class="form-group">
          {% if assignment.pk %}
          <button type="submit" class="btn btn-primary">Update</button>
          <a href="{% url 'assignments_detail' pk=assignment.pk %}" class="btn btn-danger ml-2">Go Back</a>
          {% else %}
          <button type="submit" class="btn btn-primary">Create</button>
          <a href="javascript:history.go(-1);" class="btn btn-secondary">Go Back</a>
          {% endif %}
        </div>
      </form>
    </div>
  </div>
</div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    // Initialize date picker on date fields
    $('#id_due_date').datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true,
      todayHighlight: true,
      clearBtn: true,
      orientation: 'bottom',
      container: '.fantasy-form'
    });
  });
</script>
{% endblock %}